### ISSUE TITLE
Establish New Data Structure that is easier to maintain.

### ISSUE THREAD

**Issue by rposborne** [hexorx/countries#210]
Countries list should be only Code
Sub directory of countries one yml file per country
These sub files would include all data associated with a given country including subregions. 
```
countries.yml
countries
-us.yml
-gb.yml
```

**Comment by rposborne** [comment]
See #211

**Comment by cllns** [comment]
It'd be cool if the gem handled the duplicated `name` in the `names` field.

Let me explain: the fields in the yaml files could be `:name` and `:alternate_names` (or `:other_names` perhaps). If a country/subdivision doesn't have more than one `:name`, then `:alternate_names` could be blank. 

But the API should remain backwards compatible, so someone could still call `:names` and get an array of `:name` and `:alternate_names` concat'd together.

**Comment by rposborne** [comment]
Yea, ```names``` certainly feels "redundant" as I consider it more of slang terms, certainly not derogatory slang but, things like "States" for the US or "UK" for great britain.  

The question is though, if we end up pulling data like in #211 do we even need a "name"?  Should name simple default to the english name translation?

**Comment by cllns** [comment]
Would `alternate_names` be a dictionary of ISO 639-1 language codes, or an array? Right now they're just an array, but we have no way of knowing what language they're in.

Another idea: what if the data files only had English in them, and the translations were dealt with in specific translation files? This also seems like it'd be easier to get contributors to translate country/subdivision names. They just need to add/edit one file, rather than 250+

**Comment by rposborne** [comment]
So do a quick read over #133 basically the intent is to pull the dictionary out of this gem, and depend on i1l8n_data has it pulls from debian.  Basically all the work is done.   I think ```alternate_names``` basically servers the purpose of doing lookups of a col in a database.   So I think an array is appropriate, only the official names should be translated I think,

**Comment by cllns** [comment]
Ooh, that does look good.

Yea, then it does seem like it'd make sense to get rid of name. The only reason I could think of keeping a `name` is for developers looking at files. Since I'm sure few people have the `alpha2` codes memorized.

But maybe we could keep this as a comment on the first line, rather than structured data? This name wouldn't matter much, just give developers an idea of what country they're looking at.

**Comment by rposborne** [comment]
Yup that is the idea,  I think we just leave it be, as I want to encourage the ability to reparse the yaml to ensure we keep things clean in commits, and I am not totally sure how comments are handled in that process.

**Comment by rposborne** [comment]
see #211
