### ISSUE TITLE
Deprecation warning needed for :require => 'countries/global' change

### ISSUE THREAD

**Issue by constantm** [hexorx/countries#313]
Just wasted a ton of time trying to figure out where the following comes from:

```
rake aborted!
LoadError: cannot load such file -- global
/Users/constantlm/Rails/app/config/application.rb:8:in `<top (required)>'
/Users/constantlm/Rails/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

Finally figured out it's from the `:require => 'countries/global'` change.

It's difficult keeping track of breaking changes for each gem if you use a ton of them. I think a deprecation warning would have been nice here. :)

**Comment by rposborne** [comment]
@constantm sorry that you had to go down the rabbit hole for this.   The issue was that we were clobbering the global load path with a commonly named file. I agree I moved a bit quick on this. But it's hard to provide a deprecation warning when it's the FILE that has to move vs a method change.   Especially retroactively.  If you have any ideas I am all ears but I think I have missed the boat already.

**Comment by constantm** [comment]
Understand 100%. :) I would suggest putting the old file back for a version or two which raises an exception when included, prompting the user to update the include file path. However, I assume there are issues with other libraries with the global, hence the change.

**Comment by richoakley** [comment]
Thanks for commenting about this @constantm - I just spent a ton of time trying to debug the same issue after an bundle update, so you just saved me a few hours / years of my life.
